# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name update
#' @param fftree fftree
#' @return fftree
#' @details This a somewhat internal function. Use it with caution. Normally one should use the wrapped version \code{update} instead of the direct call \code{updateFftree}.
#' @seealso \code{\link{update},\link{fftree}}
#' ...
updateFftree <- function(fftree) {
    .Call('fftrees_updateFftree', PACKAGE = 'fftrees', fftree)
}

#' Updates tree cache
#'
#' Updates trees internal caches and results without writing new cues into trees internal storage.
#'
#' @name updateFftree2
#' @param fftree fftree
#' @param cuelist list. List with cues.
#' @return fftree
#' @details Use it with caution. Normally one should use the wrapped version \code{\link{update}}. This specific variant avoids writing the used cues back into the trees internal storage to avoid the list-bottlenecks.
#' @seealso \code{\link{update},\link{fftree}}
#' ...
updateFftree2 <- function(fftree, cuelist) {
    .Call('fftrees_updateFftree2', PACKAGE = 'fftrees', fftree, cuelist)
}

